src/main/java/managedbean/CampeonatoMB.java
package managedbean;

import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import org.primefaces.event.RowEditEvent;

import cruzeirao.Campeonato;
import cruzeirao.Usuario;
import service.CampeonatoService;
import service.UsuarioService;

@ManagedBean
@SessionScoped

public class CampeonatoMB {
	
	private List<Campeonato> campeonatos;
	private Campeonato campeonatoAtual;
	private Campeonato novoCampeonato = new Campeonato();
	private CampeonatoService campeonatoService = new CampeonatoService();
	private Usuario usuarioAtual;
	private UsuarioService usuarioService = new UsuarioService();
	
	
	public String salvar() {
		novoCampeonato = campeonatoService.save(novoCampeonato);
		if(campeonatos != null) {
			campeonatos.add(novoCampeonato);
		}
		
		novoCampeonato = new Campeonato();
		return "campeonatotabela";
	}	 
	
	public void update(RowEditEvent event) {
		
		Campeonato c = ((Campeonato) event.getObject());
		novoCampeonato = campeonatoService.save(c);
	}
	
	public List<Campeonato> getCampeonatos() {
		return campeonatoService.getAll(Campeonato.class);
	}	
	
	public Campeonato getNovoCampeonato() {
		return novoCampeonato;
	}

	public void setNovoCampeonato(Campeonato novoCampeonato) {
		this.novoCampeonato = novoCampeonato;
	}	

	public void gerenciar(Usuario usuario) {
		this.novoCampeonato.setUsuario(usuario);
		//usuarioAtual = (Usuario) usuarioService.getById(Usuario.class, usuario.getEmail());
		//usuarioService.closeEntityManager();
	}
}

src/main/java/managedbean/CartaoMB.java
package managedbean;

import java.util.ArrayList;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import cruzeirao.Cartao;

@ManagedBean
@SessionScoped

public class CartaoMB {
	
	private ArrayList <Cartao> lista = 
			new ArrayList<Cartao>();
	
	private Cartao newcartao = new Cartao();
	private String relatoJuiz;
	
	public String salvar() {
		lista.add(newcartao);
		newcartao = new Cartao();
		return "cartaotabela";
	}
	 

	public ArrayList<Cartao> getLista() {
		return lista;
	}

	public void setLista(ArrayList<Cartao> lista) {
		this.lista = lista;
	}


	public Cartao getCartao() {
		return newcartao;
	}


	public void setCartao(Cartao cartao) {
		this.newcartao = cartao;
	}


	public String getRelatoJuiz() {
		return relatoJuiz;
	}


	public void setRelatoJuiz(String relatoJuiz) {
		this.relatoJuiz = relatoJuiz;
	}


	

}

src/main/java/managedbean/CategoriaMB.java
package managedbean;

import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import cruzeirao.Categoria;
import cruzeirao.Usuario;
import service.CategoriaService;


@ManagedBean
@SessionScoped

public class CategoriaMB {
	
	private Categoria categoria = new Categoria();
	private Categoria categoriaAtual;
	private CategoriaService categoriaService = new CategoriaService();
	
	public String salvar() {
		categoriaService.salvar(categoria);
		categoria = new Categoria();
		return "categoriatabela";
	}
	 

	public List<Categoria> getCategorias() {
		return categoriaService.getCategorias();
	}

	public Categoria getcategoria() {
		return categoria;
	}

	public void setcategoria(Categoria categoria) {
		this.categoria = categoria;
	}
	
	public String gerenciar(Categoria categoria) {
		categoriaAtual = (Categoria) categoriaService.getCategorias();
		return "gerenciador";
	}

}

src/main/java/managedbean/EquipeMB.java
package managedbean;

import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import org.primefaces.event.RowEditEvent;

import cruzeirao.Equipe;
import cruzeirao.Usuario;
import service.EquipeService;

@ManagedBean
@SessionScoped

public class EquipeMB {
	
	private Equipe novaEquipe = new Equipe();
	private EquipeService equipeService = new EquipeService();
	private List<Equipe> equipes;
	
	public String salvar() {
		novaEquipe = equipeService.save(novaEquipe);
		
		if(equipes != null) {
			equipes.add(novaEquipe);
		}
		
		novaEquipe = new Equipe();
		return "equipetabela";
	}
	 

	public void update(RowEditEvent event) {
		
		Equipe e = ((Equipe) event.getObject());
		novaEquipe = equipeService.save(e);
	}
	 

	public List<Equipe> getEquipes() {
		return equipeService.getAll(Equipe.class);
	}

	public Equipe getNovaEquipe() {
		return novaEquipe;
	}

	public void setEquipe(Equipe novaEquipe) {
		this.novaEquipe = novaEquipe;
	}
	
	public void gerenciar(Usuario usuario) {
		this.novaEquipe.setUsuario(usuario);
	}

}

src/main/java/managedbean/FaseMB.java
package managedbean;

import java.util.ArrayList;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import cruzeirao.Equipe;
import cruzeirao.Fase;
import service.FaseService;

@ManagedBean
@SessionScoped

public class FaseMB {
	
	/*private ArrayList <Fase> lista = 
			new ArrayList<Fase>();*/
	
	private Fase novaFase = new Fase();
	private FaseService faseService = new FaseService();
	
	public String salvar() {
		faseService.salvar(novaFase);
		novaFase = new Fase();
		return "fasetabela";
	}
	 
	public List<Fase> getFases() {
		return faseService.getFases();
	}

	/*public ArrayList<Fase> getLista() {
		return lista;
	}

	public void setLista(ArrayList<Fase> lista) {
		this.lista = lista;
	}*/


	public Fase getNovaFase() {
		return novaFase;
	}

	public void setFase(Fase novaFase) {
		this.novaFase = novaFase;
	}

	

}

src/main/java/managedbean/GolMB.java
package managedbean;

import java.util.ArrayList;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import cruzeirao.Gol;
import cruzeirao.Inscricao;
import service.GolService;


@ManagedBean
@SessionScoped

public class GolMB {
	
	private Gol gol = new Gol();
	private Gol golAtual;
	private GolService golService = new GolService();
	private ArrayList<Inscricao> times =  new ArrayList<Inscricao>();
	private ArrayList<Boolean> penaltys =  new ArrayList<Boolean>();
	
	public String salvar() {
		golService.salvar(gol);
		gol = new Gol();
		return "goltabela";
	}
	 

	public List<Gol> getGols() {
		return golService.getGols();
	}

	public Gol getgol() {
		return gol;
	}

	public void setgol(Gol gol) {
		this.gol = gol;
	}
	
	public String gerenciar(Gol gol) {
		golAtual = golService.getGolByTempo(gol.getTempo());
		return "gerenciador";
	}

}

src/main/java/managedbean/GrupoMB.java
package managedbean;

import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import cruzeirao.Grupo;
import service.GrupoService;

@ManagedBean
@SessionScoped
public class GrupoMB {
	private Grupo novoGrupo = new Grupo();
	private GrupoService grupoService = new GrupoService();
	
	public String salvar() {
		grupoService.salvar(novoGrupo);
		novoGrupo = new Grupo();
		return "grupotabela";
	}
	 
	public List<Grupo> getGrupos() {
		return grupoService.getGrupos();
	}

	public Grupo getNovoGrupo() {
		return novoGrupo;
	}

	public void setGrupo(Grupo novoGrupo) {
		this.novoGrupo = novoGrupo;
	}
}

src/main/java/managedbean/InscricaoMB.java
package managedbean;

import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import cruzeirao.Inscricao;
import service.InscricaoService;

@ManagedBean
@SessionScoped
public class InscricaoMB {
	private Inscricao novaInscricao = new Inscricao();
	private InscricaoService inscricaoService = new InscricaoService();
	
	public String salvar() {
		inscricaoService.salvar(novaInscricao);
		novaInscricao = new Inscricao();
		return "inscricaotabela";
	}
	 
	public List<Inscricao> getInscricoes() {
		return inscricaoService.getInscricoes();
	}

	public Inscricao getNovaInscricao() {
		return novaInscricao;
	}

	public void setInscricao(Inscricao novaInscricao) {
		this.novaInscricao = novaInscricao;
	}
}

src/main/java/managedbean/PartidaMB.java
package managedbean;

import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import cruzeirao.Partida;
import service.PartidaService;

@ManagedBean
@SessionScoped
public class PartidaMB {
	private Partida novaPartida = new Partida();
	private PartidaService partidaService = new PartidaService();
	
	public String salvar() {
		partidaService.salvar(novaPartida);
		novaPartida = new Partida();
		return "partidatabela";
	}
	 
	public List<Partida> getPartidas() {
		return partidaService.getPartidas();
	}

	public Partida getNovaPartida() {
		return novaPartida;
	}

	public void setPartida(Partida novaPartida) {
		this.novaPartida = novaPartida;
	}
}

src/main/java/managedbean/RodadaMB.java
package managedbean;

import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import cruzeirao.Rodada;
import service.RodadaService;

@ManagedBean
@SessionScoped
public class RodadaMB {
	private Rodada novaRodada = new Rodada();
	private RodadaService rodadaService = new RodadaService();
	
	public String salvar() {
		rodadaService.salvar(novaRodada);
		novaRodada = new Rodada();
		return "rodadatabela";
	}
	 
	public List<Rodada> getRodadas() {
		return rodadaService.getRodadas();
	}

	public Rodada getNovaRodada() {
		return novaRodada;
	}

	public void setRodada(Rodada novaRodada) {
		this.novaRodada = novaRodada;
	}
}

src/main/java/managedbean/UsuarioMB.java
package managedbean;

import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import org.primefaces.event.RowEditEvent;

import cruzeirao.Usuario;
import service.UsuarioService;

@ManagedBean
@SessionScoped

public class UsuarioMB {
	
	private Usuario novoUsuario = new Usuario();
	public Usuario usuarioAtual;
	private UsuarioService usuarioService = new UsuarioService();
	private List<Usuario> usuarios;
	
	public String salvar() {
		//usuarioService.save(novoUsuario);
		//novoUsuario = new Usuario();
		//usuarioService.closeEntityManager();
		novoUsuario = usuarioService.save(novoUsuario);
		
		if(usuarios != null) {
			usuarios.add(novoUsuario);
		}
		
		novoUsuario = new Usuario();
		return "usuariotabela";
	}
	
	public void update(RowEditEvent event) {
		
		Usuario u = ((Usuario) event.getObject());
		novoUsuario = usuarioService.save(u);
		//novoUsuario = new Usuario();
	}
	 

	public List<Usuario> getUsuarios() {
		//List<Usuario> list = usuarioService.getAll(Usuario.class);
		//usuarioService.closeEntityManager();
		return usuarioService.getAll(Usuario.class);
	}
	
	
	public void remover(Usuario usuario) {
		//novoUsuario = usuarioService.getById(Usuario.class, usuario.getEmail());
		usuarioService.remove(usuario);
		//usuarios.remove(novoUsuario);
		//novoUsuario = new Usuario();
	}

	public Usuario getNovoUsuario() {
		return novoUsuario;
	}

	public void setNovoUsuario(Usuario novoUsuario) {
		this.novoUsuario = novoUsuario;
	}
	
	public String gerenciar(Usuario usuario) {
		//usuarioAtual = (Usuario) usuarioService.getById(Usuario.class, usuario.getEmail());
		novoUsuario = usuario;
		//usuarioService.closeEntityManager();
		return "gerenciador";
	}

}

src/main/webapp/cartao.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3c.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Cartao</title>
</h:head>
<h:body>
<h2 style="m argin-top:0">Cartao</h2>
	<h:form id="formCartao">
		


			<h:panelGrid columns="2" style="margin-bottom:10px" cellpadding="5">
				<p:outputLabel for="cartao" value="Cartao:" />
				<p:selectOneRadio id="cartao" value="#{cartaoMB.setCartao(newcartao.tipo)}">
					<f:selectItem itemLabel="Vermelho" itemValue="VERMELHO" />
					<f:selectItem itemLabel="Amarelo" itemValue="AMARELO" />
				</p:selectOneRadio>
			</h:panelGrid>
			<h:panelGrid>
			<p:column>
			<p:outputLabel value="Tempo: " />
			<p:inputText value="#{cartaoMB.setCartao(newcartao.setTempo(tempo))}" />
			</p:column>
			<p:column>
			<p:outputLabel value="Relato do Juiz: " />
			<p:inputText value="#{cartaoMB.setRelatoJuiz(relatoJuiz)}" />
			</p:column>
			</h:panelGrid>
		
		<p:separator />
		<p:commandButton value="Salvar"  icon="ui-icon-disk" 
			action="#{cartaoMB.salvar}" update=":formCartao" />

		<p:commandButton value="Voltar" icon="ui-icon-arrowrefresh-1-w"
			action="menu.xhtml" />
	
</h:form>
</h:body>
</html>

src/main/webapp/categoriatabela.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3c.org/1999/xhtml"
xmlns:h="http://xmlns.jcp.org/jsf/html"
xmlns:p="http://primefaces.org/ui"
xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
xmlns:f="http://xmlns.jcp.org/jsf/core">
 <h:head>
 	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Categorias</title>
 </h:head>
 <h:body>
 <h2 style="margin-top:0">Categorias</h2>
 <h:form id="formCategoriaTabela">
<p:dataTable var="user" value="#{categoriaMB.categorias}" rows="10"
     						paginator = "true"
     						paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
     					    rowsPerPageTemplate="5,10,15">
     					    
     					    
     					    
	       <p:column headerText="Nome">
	       		<h:outputText value="#{user.nome}"/>
	       </p:column>
	       
	       <p:column headerText="Nascidos a partir de">
	       		<h:outputText value="#{user.nascidosApartirDe}"/>
	       </p:column>
	    
	    	<p:column headerText="Campeonato" >
						<h:outputText value="#{user.campeonato.nome}"/>
						<p:selectOneMenu value="#{user.campeonato}" lazy="true" style="width:125px">
							<f:selectItems value="#{campeonatoMB.campeonatos}" var="camps"
								itemLabel="#{camps.nome}" itemValue="#{camps}" />
						</p:selectOneMenu>
			</p:column>
			
			
			
	    
	        <p:column headerText="Mín. de Jogadores">
	       		<h:outputText value="#{user.minJogadores}"/>
	       </p:column>
	       
	        <p:column headerText="Máx. de Jogadores">
	       		<h:outputText value="#{user.maxJogadores}"/>
	       </p:column>
	       
	       <p:column headerText="Sexo">
	       		<h:outputText value="#{user.sexo}"/>
	       </p:column>
	 
	     
     <f:facet name="paginatorTopLeft">
            <p:commandButton type="button" icon="fa fa-sync" />
       </f:facet>
 
       <f:facet name="paginatorBottomRight">
            <p:commandButton type="button" icon="fa fa-cloud-upload" />
        </f:facet>
 
 
	
     </p:dataTable>
 	<p:separator />
     <p:commandButton value="Voltar"
     				  icon="ui-icon-arrowrefresh-1-w"
     				  action="menu.xhtml" />
     <p:commandButton value="Nova" icon="ui-icon-plus"
			action="categoria.xhtml" />	
</h:form>
</h:body>
</html>

src/main/webapp/fasetabela.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3c.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Fase</title>
</h:head>
<h:body>
<h2 style="margin-top: 0">Fase</h2>
<h:form id="formFaseTabela">
<p:dataTable var="user" value="#{faseMB.fases}" rows="10"
			paginator="true"
			paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
			rowsPerPageTemplate="5,10,15">


			<p:column headerText="Data de inicio">
				<h:outputText value="#{user.dataInicio}">
					<f:convertDateTime pattern="dd/MM/yyyy" />
				</h:outputText>
			</p:column>

			<p:column headerText="Data do fim ">
				<h:outputText value="#{user.dataFim}">
					<f:convertDateTime pattern="dd/MM/yyyy" />
				</h:outputText>
			</p:column>

			<p:column headerText="Numero">
				<h:outputText value="#{user.numero}" />
			</p:column>


			<f:facet name="paginatorTopLeft">
				<p:commandButton type="button" icon="fa fa-sync" />
			</f:facet>

			<f:facet name="paginatorBottomRight">
				<p:commandButton type="button" icon="fa fa-cloud-upload" />
			</f:facet>
		
		</p:dataTable>
		<p:separator />
		<p:commandButton value="Voltar" icon="ui-icon-arrowrefresh-1-w"
			action="menu.xhtml" />
		<p:commandButton value="Novo" icon="ui-icon-plus"
			action="fase.xhtml" />		
	</h:form>

</h:body>
</html>

src/main/webapp/grupotabela.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3c.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Grupo</title>
</h:head>
<h:body>
<h2 style="margin-top: 0">Grupo</h2>
<h:form id="formGrupoTabela">
<p:dataTable var="user" value="#{grupoMB.grupos}" rows="10"
			paginator="true"
			paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
			rowsPerPageTemplate="5,10,15">
			
			<p:column headerText="Nome">
				<h:outputText value="#{user.nome}" />
			</p:column>

			<p:column headerText="Numero">
				<h:outputText value="#{user.numero}" />
			</p:column>


			<f:facet name="paginatorTopLeft">
				<p:commandButton type="button" icon="fa fa-sync" />
			</f:facet>

			<f:facet name="paginatorBottomRight">
				<p:commandButton type="button" icon="fa fa-cloud-upload" />
			</f:facet>
		
		</p:dataTable>
		<p:separator />
		<p:commandButton value="Voltar" icon="ui-icon-arrowrefresh-1-w"
			action="menu.xhtml" />
		<p:commandButton value="Novo" icon="ui-icon-plus"
			action="nome.xhtml" />		
	</h:form>

</h:body>
</html>

src/main/webapp/inscricao.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3c.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Inscricao</title>
</h:head>
<h:body>
	<h2 style="margin-top: 0">Inscricao</h2>
	<h:form id="formInscricao">	
			
			<p:outputLabel 	value="Numero:" />
			<p:inputText value="#{inscricaoMB.novaInscricao.numero}" />
			<br />
			
			<p:outputLabel 	value="Pagamento: (true/false)" /> <!-- Alterar para radio button -->
			<p:inputText value="#{inscricaoMB.novaInscricao.pagamento}" />
			
			<br />
			<p:outputLabel 	value="Validada: (true/false)" /> <!-- Alterar para radio button -->
			<p:inputText value="#{inscricaoMB.novaInscricao.validada}" />
			
			<br />
			<p:outputLabel value = "Categoria: " />
           <p:selectOneMenu value="{categoriaMB.categoria}">
           <f:selectItem itemLabel="Selecionar" itemValue="" />
           <f:selectItems value="#{categoriaMB.categorias}" var="aux"
						itemValue="#{aux}" itemLabel="#{aux.nome}" />
			</p:selectOneMenu>
			
			<br />
			<p:outputLabel value = "Equipe: " />
           <p:selectOneMenu value="{equipeMB.equipe}">
           <f:selectItem itemLabel="Selecionar" itemValue="" />
           <f:selectItems value="#{equipeMB.equipes}" var="aux"
						itemValue="#{aux}" itemLabel="#{aux.nome}" />
			</p:selectOneMenu>
		
		<p:separator />
		<p:commandButton value="Salvar"  icon="ui-icon-disk" 
			action="#{inscricaoMB.salvar}" update=":formInscricao" />
		
		<p:commandButton value="Voltar" icon="ui-icon-arrowrefresh-1-w"
			action="menu.xhtml" />	


	</h:form>

</h:body>
</html>

src/main/webapp/inscricaotabela.xhtml
 <!DOCTYPE html>
<html xmlns="http://www.w3c.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Inscricao</title>
</h:head>
<h:body>
<h2 style="margin-top: 0">Inscricao</h2>
<h:form id="formInscricaoTabela">
<p:dataTable var="user" value="#{inscricaoMB.inscricoes}" rows="10"
			paginator="true"
			paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
			rowsPerPageTemplate="5,10,15">

			<p:column headerText="Numero">
				<h:outputText value="#{user.numero}" />
			</p:column>
			
			<p:column headerText="Pagamento">
				<h:outputText value="#{user.pagamento}" />
			</p:column>
			
			<p:column headerText="Validada">
				<h:outputText value="#{user.validada}" />
			</p:column>
			
			<p:column headerText="Categoria" >
						<h:outputText value="#{user.categoria.nome}"/>
						<p:selectOneMenu value="#{user.categoria}" lazy="true" style="width:125px">
							<f:selectItems value="#{categoriaMB.categorias}" var="x"
								itemLabel="#{x.nome}" itemValue="#{x}" />
						</p:selectOneMenu>
			</p:column>
			
			<p:column headerText="Equipe" >
						<h:outputText value="#{user.equipe.nome}"/>
						<p:selectOneMenu value="#{user.equipe}" lazy="true" style="width:125px">
							<f:selectItems value="#{equipeMB.equipes}" var="x"
								itemLabel="#{x.nome}" itemValue="#{x}" />
						</p:selectOneMenu>
			</p:column>


			<f:facet name="paginatorTopLeft">
				<p:commandButton type="button" icon="fa fa-sync" />
			</f:facet>

			<f:facet name="paginatorBottomRight">
				<p:commandButton type="button" icon="fa fa-cloud-upload" />
			</f:facet>
		
		</p:dataTable>
		<p:separator />
		<p:commandButton value="Voltar" icon="ui-icon-arrowrefresh-1-w"
			action="menu.xhtml" />
		<p:commandButton value="Novo" icon="ui-icon-plus"
			action="inscricao.xhtml" />		
	</h:form>

</h:body>
</html> 

src/main/webapp/partidatabela.xhtml
 <!DOCTYPE html>
<html xmlns="http://www.w3c.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Partida</title>
</h:head>
<h:body>
<h2 style="margin-top: 0">Partida</h2>
<h:form id="formPartidaTabela">
<p:dataTable var="user" value="#{partidaMB.partidas}" rows="10"
			paginator="true"
			paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
			rowsPerPageTemplate="5,10,15">

			<p:column headerText="Numero">
				<h:outputText value="#{user.numero}" />
			</p:column>

			<f:facet name="paginatorTopLeft">
				<p:commandButton type="button" icon="fa fa-sync" />
			</f:facet>

			<f:facet name="paginatorBottomRight">
				<p:commandButton type="button" icon="fa fa-cloud-upload" />
			</f:facet>
		
		</p:dataTable>
		<p:separator />
		<p:commandButton value="Voltar" icon="ui-icon-arrowrefresh-1-w"
			action="menu.xhtml" />
		<p:commandButton value="Novo" icon="ui-icon-plus"
			action="partida.xhtml" />		
	</h:form>

</h:body>
</html> 